name: "receipt-extractor-prod"
services:
  database:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./server/.env.production
    volumes:
      - receipt-extractor:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    image: ${DOCKER_USERNAME}/receipt-extractor-server:${IMAGE_TAG}
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env.production
    networks:
      - app-network
    depends_on:
      - database
    restart: unless-stopped
    user: "node"

  client:
    image: ${DOCKER_USERNAME}/receipt-extractor-client:${IMAGE_TAG}
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.production
    networks:
      - app-network
    restart: unless-stopped
    user: "node"

networks:
  app-network:
    driver: bridge

volumes:
  receipt-extractor:
