name: "receipt-extractor"
services:
  database:
    image: postgres:14.18
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - receipt-extractor:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      - app-network
    depends_on:
      - database
    restart: unless-stopped
    user: "node"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    networks:
      - app-network
    restart: unless-stopped
    user: "node"

networks:
  app-network:
    driver: bridge

volumes:
  receipt-extractor:
