FROM node:lts-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN chmod +x /app/entrypoint.sh
RUN pnpm prisma generate && pnpm tsc

EXPOSE 5000

CMD ["/app/entrypoint.sh"]
