FROM node:lts-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm prisma generate && pnpm tsc

EXPOSE 5000

CMD ["sh", "-c", "pnpm prisma db push && node dist/index.js"]
